### ISSUE TITLE
install phase stuck in "Fetching git@github.com:johnsundell/require.git"

### ISSUE THREAD

**Issue by frankxzx** [JohnSundell/TestDrive#10]
I'm new to swift package manger, can you provide some advices to deal with this problem, thanks.

**Comment by JohnSundell** [comment]
@frankxzx Do you have an SSH key registered with GitHub and have you added it to `ssh-agent`? If not, here's a help article from GitHub explaining how to do it: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/ 🙂

**Comment by dreymonde** [comment]
@JohnSundell btw, why are you using `git@` instead of `https://` in all your Package.swift files? https access works on Mac nicely without any additional work, and (as I was told) it’s more secure than git@

**Comment by JohnSundell** [comment]
@dreymonde I should probably switch to HTTPS, since I'm getting quite an amount of support requests like this. Either that, or include a pre-check step to check it SSH is setup. I mostly use SSH out of habit I guess. Isn't it still the case that you have to input your username/password every time you push if you use HTTPS?

**Comment by dreymonde** [comment]
@JohnSundell on Mac definitely no (you type your username/password once and then if will store them to keychain), on Linux — not sure, however I’m certain that `git clone https://...` never asked me for password on Linux

**Comment by dreymonde** [comment]
Either way, even such large primarily-Linux Swift codebases as Zewo are using `https://`, so I don’t think there will be any issues 😄

**Comment by JohnSundell** [comment]
@dreymonde Yeah, you're probably right 👍 I'll switch over to HTTPS as soon as possible (I need to work around a bug in the Swift Package Manager when both HTTPS & SSH are used first, since otherwise I need to update all of my projects at once - and all the versions need to be synced 😅)

**Comment by JohnSundell** [comment]
@frankxzx Did the suggested solution work for you - can this be closed? 🙂
