### ISSUE TITLE
Can't initialize Charts framework with TestDrive

### ISSUE THREAD

**Issue by matepapp** [JohnSundell/TestDrive#15]
I just wanted to try out the [Charts framework](https://github.com/danielgindi/Charts) and everytime I tried to run `testdrive Charts` (or with the git URL) I've always got this message.
``` shell
🕵️‍♀️  Finding pod 'Charts'...
📦  Cloning https://github.com/danielgindi/charts.git...
📋  Checking out 3.0.2...

💥  ShellOutError(message: "error: pathspec \'3.0.2\' did not match any file(s) known to git.", output: "")
```
Is it a bug or am I doing something wrong? 

_I've also tried [Alamofire](https://github.com/Alamofire/Alamofire) and [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON) to make sure the `testdrive` command does what it should and it worked with those frameworks seamlessly._

**Comment by JohnSundell** [comment]
@matepapp It seems like you're running an old version fo Test Drive. It works for me on the latest `master`. Can you re-install it and try again? 🙂

**Comment by matepapp** [comment]
@JohnSundell I've installed it 2 hours ago and the latest commit was 2 days ago so I guess I have the last version. But I've deleted and installed it again and I still get that error message.

**Comment by JohnSundell** [comment]
@matepapp Did you install it using Marathon? If so, can you try updating your packages by running `marathon update` anywhere on the command line?

**Comment by JohnSundell** [comment]
(Need to add support for version pinning soon 😅)

**Comment by matepapp** [comment]
@JohnSundell Actually I used Swift Package Manager to install testdrive. But after your suggestion I've deleted it and reinstalled with Marathon. Right now it works properly!
**Thanks for your support!** 🙌🏼

**Comment by JohnSundell** [comment]
@matepapp Awesome! 🎉 Happy test driving 🚗
