### ISSUE TITLE
multiple pods working together.

### ISSUE THREAD

**Issue by navisingh** [JohnSundell/TestDrive#2]
$ testdrive SwiftyJSON Files
creates a workspace with SwiftyJSON and Files.
I can use the scheme for SwiftyJSON, or the scheme for Files.
But I can't use both in the same playground.
It would be neat if I could have a scheme that has multiple pods.

**Comment by JohnSundell** [comment]
@navisingh This should work. But you have to build the schemes individually first (should probably add some help text for that). So first select `SwiftyJSON iOS` in the schemes dropdown - build, then select `Files-iOS` and build again. You should now be able to use both in the playground, like this:

![screen shot 2017-04-28 at 20 33 21](https://cloud.githubusercontent.com/assets/2466701/25542233/f20af39e-2c51-11e7-9ae8-cd250cc186df.png)

**Comment by JohnSundell** [comment]
@navisingh Can this be closed?

**Comment by JohnSundell** [comment]
Ping @navisingh 😄

**Comment by JohnSundell** [comment]
Closing this for now
