### ISSUE TITLE
Can't install TestDrive

### ISSUE THREAD

**Issue by hashemp206** [JohnSundell/TestDrive#21]
Just tried to install with swift package manager, got this error: 
`reference to generic type 'Array' requires arguments in <...>`

<img width="770" alt="screen shot 2017-05-26 at 12 52 33 pm" src="https://cloud.githubusercontent.com/assets/3206748/26486879/3dd286ae-4212-11e7-9bbf-a8816f54b9d3.png">

any idea?

**Comment by JohnSundell** [comment]
Update to the latest version of Xcode, which will give you Swift 3.1 (which TestDrive requires) and everything should work 👍
