### ISSUE TITLE
Fails to install via maraton

### ISSUE THREAD

**Issue by icanzilb** [JohnSundell/TestDrive#3]
Following the README, I got the following output:

```
marin:Developer marin$ marathon install TestDrive/Sources/TestDrive.swift
🏃  Updating packages...
   Cloning git@github.com:johnsundell/xgen.git...
   Resolving latest major version for git@github.com:johnsundell/xgen.git...
   Updating packages...
   Cloning git@github.com:johnsundell/files.git...
   Resolving latest major version for git@github.com:johnsundell/files.git...
   Updating packages...
   Cloning git@github.com:johnsundell/shellout.git...
   Resolving latest major version for git@github.com:johnsundell/shellout.git...
   Updating packages...
   Cloning git@github.com:johnsundell/releases.git...
   Resolving latest major version for git@github.com:johnsundell/releases.git...
   Updating packages...
   Compiling script...
💥  Failed to compile script
```

and then on subsequent runs this:

```
marin:Developer marin$ marathon install TestDrive/Sources/TestDrive.swift --verbose
🏃  $ cd "/Users/marin/.marathon/Scripts/Cache/-Users-marin-Developer-TestDrive-Sources-TestDrive/" && readlink OriginalFile
   /Users/marin/Developer/TestDrive/Sources/TestDrive.swift
   Compiling script...
   $ cd "/Users/marin/.marathon/Scripts/Cache/-Users-marin-Developer-TestDrive-Sources-TestDrive/" && swift build --enable-prefetching -c release -Xswiftc -static-stdlib
   Compile Swift Module 'Testdrive' (1 sources)
   sh: /Users/marin/Developer/Xcode: No such file or directory
💥  Failed to compile script
```

I have the latest marathon installed

**Comment by navisingh** [comment]
I went into the Testdrive folder and ran the script. that worked.

**Comment by JohnSundell** [comment]
Very interesting. @icanzilb this is after the SSH issues you mentioned earlier were resolved, right? What happens if you run the script using `marathon run TestDrive/Sources/TestDrive.swift`?

**Comment by icanzilb** [comment]
@JohnSundell 

```
marin:Developer marin$ marathon run TestDrive/Sources/TestDrive.swift
💥  Failed to compile script
```

**Comment by icanzilb** [comment]
Here's the verbose output:

```
marin:Developer marin$ marathon run TestDrive/Sources/TestDrive.swift --verbose
🏃  $ cd "/Users/marin/.marathon/Scripts/Cache/-Users-marin-Developer-TestDrive-Sources-TestDrive/" && readlink OriginalFile
   /Users/marin/Developer/TestDrive/Sources/TestDrive.swift
   $ cd "/Users/marin/.marathon/Scripts/Cache/-Users-marin-Developer-TestDrive-Sources-TestDrive/" && swift build --enable-prefetching
   Compile Swift Module 'Require' (1 sources)
   Compile Swift Module 'ShellOut' (1 sources)
   Compile Swift Module 'Files' (1 sources)
   Compile Swift Module 'Releases' (4 sources)
   Compile Swift Module 'Xgen' (5 sources)
   Compile Swift Module 'Testdrive' (1 sources)
   Linking ./.build/debug/Testdrive
   sh: /Users/marin/Developer/Xcode: No such file or directory
💥  Failed to compile script
```

**Comment by icanzilb** [comment]
@JohnSundell  Do you make any assumptions where Xcode is located on the hard drive?

**Comment by JohnSundell** [comment]
@icanzilb Nope, it doesn't even look like the error is coming from Marathon itself - it looks like it's an underlying error generated from the Swift Package Manager. Maybe it's using `xcodebuild` and it can't find your Xcode installation or something... 🤔

Can you reproduce the error by going into `/Users/marin/.marathon/Scripts/Cache/-Users-marin-Developer-TestDrive-Sources-TestDrive/` and running `swift build`?

**Comment by icanzilb** [comment]
@JohnSundell yeah, it seems it's spm can't find Xcode ... 

```
marin:-Users-marin-Developer-TestDrive-Sources-TestDrive marin$ pwd
/Users/marin/.marathon/Scripts/Cache/-Users-marin-Developer-TestDrive-Sources-TestDrive
marin:-Users-marin-Developer-TestDrive-Sources-TestDrive marin$ swift build
sh: /Users/marin/Developer/Xcode: No such file or directory
```

**Comment by JohnSundell** [comment]
@icanzilb Just to double-check, can you create a new directory anywhere on your file system, then `cd` into it and run `swift init --type executable` and then `swift build`? Just to confirm that you get the same issue (in which case it's clear that it's a SPM error)

**Comment by JohnSundell** [comment]
Sorry for making you perform so many tests, but it really helps in finding the root cause of the issue 😅

**Comment by icanzilb** [comment]
Sure thing ... I haven't played with SPM at all before so I might be missing something very simple 

```
marin:Desktop marin$ mkdir JSundell
marin:Desktop marin$ cd JSundell/
marin:JSundell marin$ swift init --type executable
error: unable to invoke subcommand: /Users/marin/Developer/Xcode 8.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-init (No such file or directory)
```

**Comment by JohnSundell** [comment]
@icanzilb Very interesting. Probably something that isn't configured the way SPM expects on your system. Let's see how your `xcode-select` is configured. What happens if you run `xcode-select -p`? Do you get the same path as SPM is trying to access? Also, where is Xcode **actually** located on your file system?

**Comment by icanzilb** [comment]
here's xcode-select:

```
marin:final marin$ xcode-select -p
/Users/marin/Developer/Xcode 8.3.app/Contents/Developer
```

And this is the actual path on my hard drive: 
```
marin:Developer marin$ pwd
/Users/marin/Developer/Xcode 8.3.app/Contents/Developer
```

Browsing through the contents of the toolchain bin I see this:

![image](https://cloud.githubusercontent.com/assets/633862/25566773/c26e8084-2de0-11e7-9bda-8bc978c74311.png)

There really isn't a `swift-init` binary found in there ... Should there be one @JohnSundell  ?

**Comment by icanzilb** [comment]
Ah, my bad I thought there ought to be a `swift-init` but now I see the command that fails is `swift init`. Well, the paths look correct anyway, not sure why does spm fail 🤔

**Comment by JohnSundell** [comment]
@icanzilb Yeah it's very curious indeed 🤔 @aciidb0mb3r @neonichu @ddunbar is the above any issue that you've seen before, where SPM can't seem to find the Xcode installation?

**Comment by JohnSundell** [comment]
@icanzilb Just spoke with @aciidb0mb3r on Twitter, and first off I'm so sorry but I made a mistake when asking you to run `swift init` - it should of course be `swift package init` 😅. But it seems like the problem is the name of your Xcode app - that it contains a space. Can you rename it to simply be `Xcode` and try again? We should also file a JIRA ticket on the SPM project to make it handle spaces in the Xcode path. Do you want to do that, otherwise I can take care of it?

**Comment by icanzilb** [comment]
@JohnSundell it's not the space that is the problem 🤔

```
marin:Developer marin$ marathon install TestDrive/Sources/TestDrive.swift
🏃  Compiling script...
💥  Failed to compile script
marin:Developer marin$ xcode-select -p
/Users/marin/Developer/Xcode8.3.app/Contents/Developer
marin:Developer marin$
```

**Comment by icanzilb** [comment]
also:

```
marin:Developer marin$ xcode-select -p
/Users/marin/Developer/Xcode.app/Contents/Developer
marin:Developer marin$ marathon install TestDrive/Sources/TestDrive.swift
🏃  Compiling script...
💥  Failed to compile script
marin:Developer marin$
```

**Comment by icanzilb** [comment]
oh, it finally worked when I renamed to Xode.app it needed a while to figure out the change though. Could the Xcode.app name be hardcoded somewhere? 😳

**Comment by JohnSundell** [comment]
@icanzilb Yeah it seems like SwiftPM assumes that Xcode will always be named `Xcode.app`. I'll file a JIRA ticket about that. Super happy that it worked out in the end! 🎉 Happy test driving 🚗

**Comment by neonichu** [comment]
Hard to say what's going on here without digging deeper, but I'd say it is unlikely that SwiftPM is the culprit in assuming Xcode is present as `/Applications/Xcode.app`. I use it it on a daily basis while being installed in other places.

I think a good starting place would be checking if `swift` itself might be a shim provided by tools such as chswift or so.
