### ISSUE TITLE
Unable to install testdrive using swift package manager

### ISSUE THREAD

**Issue by rizwan95** [JohnSundell/TestDrive#31]
Hi John, I am unable to install Testdrive using swift package manager. I am using Marathon to install it. 

Here is the command which I executed
`marathon install johnsundell/testdrive`
I am getting the following error logs. 
> 🏃  Cloning https://github.com/johnsundell/testdrive.git...
>    Compiling script...
> 💥  Failed to compile script

Please help.

**Comment by JohnSundell** [comment]
@rizwan95 mentioned on Twitter that it was solved. So closing this 🙂

**Comment by rizwan95** [comment]
Yes :)
