### ISSUE TITLE
Test SPM packages 

### ISSUE THREAD

**Issue by kimdv** [JohnSundell/TestDrive#33]
Hi @JohnSundell ! 👋👋👋
Is it possible to test SPM instead of Pods?

**Comment by JohnSundell** [comment]
Hi @kimdv 👋 Not yet, since you can't yet use a Swift Package in an Xcode Playground. Hopefully that will be possible in future versions of Xcode. Thankfully, most projects (should) offer both CocoaPods and SPM support.

**Comment by kimdv** [comment]
Thanks for reply!

I will wait then, this project doesn't support pods, Server-side-swift 🚀

Have a nice day 😎
