### ISSUE TITLE
"a version component with an unrecognized format"

### ISSUE THREAD

**Issue by gavineadie** [JohnSundell/TestDrive#4]
First time use .. curiosity!  Installed on macOS 10.12.4 without complaint using SPM, but when I tried to invoke it with a local git repo, I got:

    testdrive https://ramsay-server.local/git/SatKit.git -p macOS 
    Cloning https://ramsay-server.local/git/SatKit.git...
    Resolving latest version...
    Encountered a version component with an unrecognized format: 'DV-2016-03-09#1^{}'

That's not a version code I use (in fact that String isn't anywhere in my code!) ..

**Comment by gavineadie** [comment]
.. and invokations was:

    testdrive https://ramsay-server.local/git/SatKit.git -p macOS

**Comment by reeichert** [comment]
About this suffix "^{}", already has a fix here https://github.com/JohnSundell/Releases/commit/c41fe57197b1cee598400fe2060c3e3f4433ebbd 

try to run `marathon update` and install TestDrive again

**Comment by JohnSundell** [comment]
@gavineadie Can you show me the output of running `git ls-remote https://ramsay-server.local/git/SatKit.git`? It looks like Releases is unable to parse your the format that repo is using, but no worries - we'll have it fixed in no time 😄

**Comment by gavineadie** [comment]
Thanks, John .. A have to admit that git is a little of a black box on the server side, but it's now clear where my unrecognized `DV-2016-03-09` came from!  That's a tag marking the date of an authorship transition which I had forgotten.

    ~ gavin$ git ls-remote https://ramsay-server.local/git/SatKit.git
    9e3b72b566f14cb645a6300a3555888943c6521a	HEAD
    54c519cc17285600c8af7ffc0a4bd8e349788702	refs/heads/DV-2016-03-09
    12e9da7c020192d95d77c8d056eb6e66d50eaa7f	refs/heads/Swift
    820d2003c85168333e449d811a832eb6623c4027	refs/heads/Swift3
    9e3b72b566f14cb645a6300a3555888943c6521a	refs/heads/master
    39529ce0b97213c8713ebe9f3f923565bb633907	refs/heads/pre-cleanup
    1c776a97c60cd23b16ff7c8f28700caa6936d208	refs/tags/1.0.0
    62d8b67a6f96366f010b21cd7a904c6abf0c19d7	refs/tags/1.0.0^{}
    e98bf8764ab15072220970aa340c9f0b57b64ada	refs/tags/101
    6bbd62e98b80c994432af38f6915a3d13eaf732d	refs/tags/101^{}
    2d71881beeb44fd45f38e26637f0f8e97e103176	refs/tags/DV-2016-03-09#1
    cf89b8a424f709869f09d6ac9bbd91391c0dce68	refs/tags/DV-2016-03-09#1^{}
    7aff30e831dd3e2aee7bee22a5347d64d623b62d	refs/tags/Xcode7.1
    fbc2f5847a3e16f2b6b5bd450e534416eecc6cb0	refs/tags/Xcode7.1^{}

After I posted this question, I explored your other work and started to appreciate the existence of a set of software surrounding TestDrive.  Having only read about TestDrive, I probably missed some subtle aspects.  The suite looks interesting and useful and I've widened my exploration to read more about it.  Nice work.

**Comment by JohnSundell** [comment]
@gavineadie Thanks! 👍 It looks like [Releases](https://github.com/johnsundell/releases) needs to be patched to ignore strings like `DV-2016-03-09`. Turns out people are using tags in ways that I didn't expect 😅 I'll try to find time to work on a fix tomorrow, if no one beats me to it and submits a PR 🙂

**Comment by gavineadie** [comment]
Not urgent for me .. get to it when you can .. no rush !

**Comment by JohnSundell** [comment]
@gavineadie Releases has now been patched to ignore non semantic version tags - so you should now be able to use TestDrive with your repository. If you installed through the Swift Package Manager, you need to run `swift package update` before re-installing TestDrive, and if you installed through Marathon you'll need to run `marathon update` before re-installing. (At some point I'll work on making that update process simpler 😅)

Let me know if this patch fixes the issue 👍

**Comment by gavineadie** [comment]
Maybe it's me, but I'm getting a new error.  First the `git ls-remote`

```
gavin$ git ls-remote https://ramsay-server.local/git/SatKit.git
a27b54a963bc2de22a4fa82ee4eb2348409fd2ba	HEAD
54c519cc17285600c8af7ffc0a4bd8e349788702	refs/heads/DV-2016-03-09
12e9da7c020192d95d77c8d056eb6e66d50eaa7f	refs/heads/Swift
820d2003c85168333e449d811a832eb6623c4027	refs/heads/Swift3
a27b54a963bc2de22a4fa82ee4eb2348409fd2ba	refs/heads/master
39529ce0b97213c8713ebe9f3f923565bb633907	refs/heads/pre-cleanup
079d3d8dac45cf3b1ec6cc57dd3241c3db3a1255	refs/tags/1.0.0
62d8b67a6f96366f010b21cd7a904c6abf0c19d7	refs/tags/1.0.0^{}
c82f086e97710790729f1fbfa821a18f2d168af6	refs/tags/1.0.1
6bbd62e98b80c994432af38f6915a3d13eaf732d	refs/tags/1.0.1^{}
2d71881beeb44fd45f38e26637f0f8e97e103176	refs/tags/DV-2016-03-09#1
cf89b8a424f709869f09d6ac9bbd91391c0dce68	refs/tags/DV-2016-03-09#1^{}
7aff30e831dd3e2aee7bee22a5347d64d623b62d	refs/tags/Xcode7.1
fbc2f5847a3e16f2b6b5bd450e534416eecc6cb0	refs/tags/Xcode7.1^{}
```

.. then the error:

```
gavin$ testdrive https://ramsay-server.local/git/SatKit.git -p macOS
📦  Cloning https://ramsay-server.local/git/SatKit.git...
🚢  Resolving latest version...
📋  Checking out version Xcode7.1.0...
💥  ShellOutError(message: "error: pathspec \'Xcode7.1.0\' did not match any file(s) known to git.", output: "")
```

**Comment by JohnSundell** [comment]
@gavineadie Ah, we're making progress at least 😄 The problem now is that Releases assumes that all versions will have 3 components - will have to patch that as well. I'm also thinking about adding a launch argument to skip versioning all together, and simply check out master.

**Comment by JohnSundell** [comment]
@gavineadie Just made another patch for Releases. It should now correctly parse the tag Xcode7.1, however it will check out that version as it considers it the most recent version (since 7 is the highest number). I think the simplest way to work around this is to enable you to skip versioning, or specify a specific version to check out when calling Test Drive. So it would be something like:

```
$ testdrive https://ramsay-server.local/git/SatKit.git --version 1.0.1
```

or

```
$ testdrive https://ramsay-server.local/git/SatKit.git --master
```

**Comment by JohnSundell** [comment]
@gavineadie Another option is for you to delete the tag `Xcode7.1`, if you no longer need it that is 😇

**Comment by gavineadie** [comment]
In addition to my non-semantic marker tags, I did have a "1.0.0" and a "101" earlier, so I wasn't internally consistent. I'll have to go and look at the semantic version conventions again and correct my behavior; I wasn't paying to tag values when this project started.

I second the idea of simply checking out master as an option .. before I realized that Releases was for managing releases (!), I assumed that master would be the selected one.

**Comment by JohnSundell** [comment]
There we go, you can now pass either `--master` or `-m` to use the master branch for any pod/framework, or `--version`/`-v` to check out a specific version. For example:
```
$ testdrive https://ramsay-server.local/git/SatKit.git --version 1.0.1
```

@gavineadie Let me know if that fixes the issue 👍

**Comment by JohnSundell** [comment]
@gavineadie Do you mind if I close this?

**Comment by gavineadie** [comment]
Ok to close. Sorry for not getting back, I'm traveling this week. 

.. Sent by iPhone

**Comment by JohnSundell** [comment]
@gavineadie No worries at all, I know exactly what it's like 😄 Closing for now, feel free to open a new issue or comment on here if you still encounter any issues test driving your project.
