### ISSUE TITLE
Crashes with RealmSwift

### ISSUE THREAD

**Issue by icanzilb** [JohnSundell/TestDrive#7]
```
🕵️‍♀️  Finding pod 'RealmSwift'...
📦  Cloning https://github.com/realm/realm-cocoa.git...
🚢  Resolving latest version...

💥  Encountered a version component with an unrecognized format: 'before_ios_render_optimization'
```

**Comment by JohnSundell** [comment]
Ah, this is essentially the same issue as https://github.com/JohnSundell/TestDrive/issues/4. It seems that [Releases](https://github.com/johnsundell/releases) needs to be less sensitive to tags that are not semantic versions. Will fix this one tonight 👍

**Comment by JohnSundell** [comment]
@icanzilb I've now patched Releases to work with non-semantic version git tags, so it can correctly parse RealmSwift's versions and the playground opens successfully 👍 However, it doesn't seem like RealmSwift can compile inside of a playground 😢

I get the following errors:
![screen shot 2017-05-01 at 21 33 07](https://cloud.githubusercontent.com/assets/2466701/25591684/cdf87f88-2eb5-11e7-90cc-57c8b26295dd.png)

**Comment by JohnSundell** [comment]
I don't think Swift playgrounds are compatible with C++, but I might be mistaken.

**Comment by icanzilb** [comment]
There is a playground in the Realm repo, which showcases how to do some simple stuff with Realm. Further I've been using https://github.com/segiddins/ThisCouldBeUsButYouPlaying ( a long time ago when it was working) to create playgrounds with Realm / RxSwift so it ought to be possible

**Comment by icanzilb** [comment]
I can give it another try in the following days, try to understand what exactly is the issue

**Comment by JohnSundell** [comment]
@icanzilb I solved it 🎉 The problem was that Test Drive wasn't checking out submodules, which RealmSwift is using. Fixed it here: https://github.com/JohnSundell/TestDrive/commit/bd9be5c8e758a6b4edff91bfb3901cfccab438ab. Let me know if it works for you as well 👍

**Comment by icanzilb** [comment]
@JohnSundell it's still failing for me, here's what I've been trying to do:

```
marin:Developer marin$ rm -Rf TestDrive
marin:Developer marin$ marathon install TestDrive/Sources/TestDrive.swift
💥  Could not find a Swift script at 'TestDrive/Sources/TestDrive.swift'
👉  Please check that the path is valid and try again
marin:Developer marin$ git clone git@github.com:JohnSundell/TestDrive.git
Cloning into 'TestDrive'...
remote: Counting objects: 80, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 80 (delta 12), reused 0 (delta 0), pack-reused 51
Receiving objects: 100% (80/80), 2.46 MiB | 616.00 KiB/s, done.
Resolving deltas: 100% (30/30), done.
Checking connectivity... done.
marin:Developer marin$ marathon install TestDrive/Sources/TestDrive.swift
🏃  Compiling script...
   Installing binary...
⚠️  A binary already exists at /usr/local/bin/testdrive
❓  Are you sure you want to overwrite it? (Type 'Y' to confirm)
Y
💻  TestDrive/Sources/TestDrive.swift installed at /usr/local/bin/testdrive
marin:Developer marin$ testdrive RxSwift RxCocoa RealmSwift RxRealm --verbose
🕵️‍♀️  Finding pod 'RxSwift'...
📦  Cloning https://github.com/reactivex/rxswift.git...
🚢  Resolving latest version...
📋  Checking out version 3.4.1...
🚗  Rx is ready for test drive

🕵️‍♀️  Finding pod 'RxCocoa'...
♻️  Reusing clone of rxswift

🕵️‍♀️  Finding pod 'RealmSwift'...
📦  Cloning https://github.com/realm/realm-cocoa.git...
🚢  Resolving latest version...

💥  Encountered a version component with an unrecognized format: 'before_ios_render_optimization'
```

**Comment by JohnSundell** [comment]
@icanzilb Looks like haven't got the patch to Releases that fixes the unrecognized tag format bug. Try running `marathon update` and then re-install Test Drive again. At some point I really want to add support for version pinning to Marathon - to avoid these kind of issues.

**Comment by icanzilb** [comment]
oh, didn't realize I had to update Marathon first, now it's okay! thanks

**Comment by JohnSundell** [comment]
Happy you're finally able to test drive @icanzilb! Let me know how you like the tool 😄
