### ISSUE TITLE
Doesn't recognize DateToolsSwift (possible issue with the repo structure)

### ISSUE THREAD

**Issue by UberJason** [JohnSundell/TestDrive#8]
Hi there,

<img width="653" alt="screen shot 2017-05-01 at 1 16 33 pm" src="https://cloud.githubusercontent.com/assets/5779307/25587081/72aa12b2-2e70-11e7-9acc-e06fab600b2a.png">

I tried running TestDrive with `DateToolsSwift`, but the generated playground did not recognize the module `DateToolsSwift`.

However, I did notice that it _does_ recognize the module `DateTools`. If you look at the [DateTools repo](https://github.com/MatthewYork/DateTools), the author actually has two Cocoapods there - DateTools (the old Obj-C library) and DateToolsSwift (the library re-written in Swift). Each one has a folder for itself that contains a `DateToolsExample` project. TestDrive seems to be pulling the example and corresponding frameworks from the Obj-C project `DateTools` rather than the desired `DateToolsSwift` project.

Not sure if this is helpful or not, but perhaps worth a look? Cocoapods is able to pull the correct pod out of this repo, so ideally TestDrive would be able to as well.

**Comment by JohnSundell** [comment]
Thanks for reporting this issue @UberJason! It's indeed something we should fix. Right now we simply search for an Xcode project in the repo, and as soon as one is found, we return it. But an improvement (and something that I believe would fix this issue) would be to first search for an **exact** match (in this case we would match against `DateToolsSwift`) before performing a more wide search.

**Comment by JohnSundell** [comment]
@UberJason Just took a closer look at the DateTools repo, and it looks like it doesn't actually contain an Xcode project - which makes it incompatible with Swift playgrounds. That's why TestDrive uses the example project - because that's the only thing it can find.

**Comment by UberJason** [comment]
@JohnSundell Each pod has an example project, though, which are named the same but actually contain different things (see [here](https://github.com/MatthewYork/DateTools/tree/master/DateToolsSwift/Examples/DateToolsExample) and [here](https://github.com/MatthewYork/DateTools/tree/master/DateTools/Examples/DateToolsExample)). Both are example projects called "DateToolsExample" but they're different. Do you think your tool could look for example projects within certain directories, or do some sort of "closest match" if there's more than one Xcode project?

**Comment by JohnSundell** [comment]
@UberJason Yeah, I still think we should do that. But it won't help in the case of DateTools, since Swift playgrounds needs a framework target for all dependencies - and the DateToolsExample projects are for app targets... Basically DateTools needs to define an Xcode project with a framework target for it to work with a Swift playground (no matter what Test Drive does).

**Comment by JohnSundell** [comment]
That is, until I find the time to make [Xgen](https://github.com/johnsundell/xgen) able to generate Xcode projects 😅

**Comment by UberJason** [comment]
Interesting. One thing still confuses me though - why was TestDrive able to find the Obj-C DateTools library and successfully import that into the Playground? Did the library author make the Obj-C DateToolsExample project have a framework target for DateTools, but not do the same for the Swift DateToolsExample project?

**Comment by JohnSundell** [comment]
@UberJason It just picked the first Xcode project that it found - it's not smart enough to know whether an Xcode project is for a framework or not 🙂

**Comment by JohnSundell** [comment]
@UberJason You can see the Xcode project searching code here: https://github.com/JohnSundell/TestDrive/blob/master/Sources/TestDrive.swift#L193

**Comment by UberJason** [comment]
I see the situation now that I've looked at the Swift and Obj-C DateToolsExample projects. The author actually did make a DateTools framework in the Obj-C version of the example, but didn't make a DateTools framework in the Swift version of the example. So it was lucky that TestDrive found the Obj-C example project, which contained the framework. Thanks for the clarification! 

I love the idea of TestDrive and would be excited if and when you get the time to make it able to generate Xcode projects for Pods that don't already have a framework target. I know Cocoapods is able to take Pods that don't have framework targets (just a set of files) and then create frameworks out of them with the `use_frameworks!` command, so hopefully that's something you'll consider in the future, maybe with Xgen. Thanks already for this great tool!

**Comment by JohnSundell** [comment]
@UberJason Yeah for sure, I would love to be able to do that. The only reason it's not yet supported is because it's really complicated 😞 Xgen is able to generate Playgrounds and Workspaces, because they are simply XML files, but Xcode projects are using the old-style Plist format, which is a lot harder to work with. Anyway, hopefully we can make it happen in the future 👍 Happy you like Test Drive! Let me know if you encounter any other issues, I'd be happy to help 🙂
