### ISSUE TITLE
problem testdriving a pod that depends on another pod

### ISSUE THREAD

**Issue by spinach** [JohnSundell/TestDrive#9]
Great repo, thank you for sharing your work! 

I am struggling with testdriving a pod `B` that depends on pod `A`.

I tried:

- `testDrive B`
- `testDrive B A`

In both cases I get a pod problem 

> diff: /../Podfile.lock: No such file or directory

I tried to do a pod install inside project `B` but it didn't work. 

To repro: 

- `testdrive InstantSearch-Core-Swift`

OR 

- `testdrive AlgoliaSearch-Client-Swift InstantSearch-Core-Swift`

**Comment by JohnSundell** [comment]
Thanks for reporting this @spinach! This is indeed something we should support - I can look into it sometime during the next few days if no-one beats me to it 😄

**Comment by JohnSundell** [comment]
@spinach Took a quick look at it now, and I got it to work by first running:
```
$ testdrive AlgoliaSearch-Client-Swift InstantSearch-Core-Swift
```
and then removing all CocoaPods-related build phases for the `InstantSearchCore-iOS` target, making it look like this:
![screen shot 2017-05-02 at 18 46 28](https://cloud.githubusercontent.com/assets/2466701/25628788/c78d5f1c-2f67-11e7-9858-6920edc39927.png)

Ideally this would be automatic, but at least this is a workaround for now 👍

**Comment by JohnSundell** [comment]
I think most pods with dependencies will actually work by just specifying both pods to `testdrive`, but the problem here is that the Xcode project itself is too tightly integrated with CocoaPods to work directly in a Swift playground.

**Comment by spinach** [comment]
That's awesome, thank you for solution!

I totally get the coupling problem.. But for now that works! 

You can re-open the issue in case you find a way to automate it, or if you want to keep it open :)

**Comment by JohnSundell** [comment]
@spinach Let's see if it becomes a more widely reported issue, if so I'll create a new issue to work on an automated solution at some point. Happy the solution worked for you 🎉
